backend:
  name: github
  repo: van0kLynx/hugo-blogposts
  branch: main
  auth_scope: "repo"
  base_url: "https://github.com/login/oauth/authorize"
  auth_endpoint: "https://github.com/login/oauth/access_token"
  client_id: "Ov23liG2cXs8T4YfxhoM"
  client_secret: "4b335a5e71be597485ad888529116af8a68bff66"

site_url: "https://van0kLynx.github.io/hugo-blogposts/admin/" # GitHub Pages URL

media_folder: "assets/uploads"     # Folder where uploaded media will be stored
public_folder: "/public/images"     # Public URL for accessing media files

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm" }
      - { label: "Cover Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
