backend:
  name: git-gateway
  repo: van0kLynx/hugo-blogposts  # Your GitHub repository
  branch: main  # The branch you want to use
  base_url: https://api.netlify.com
  auth_endpoint: /auth
  publish_mode: editorial_workflow

site_url: "https://helpful-gumdrop-4afd41.netlify.app"  # Replace with your Netlify site URL

media_folder: "static/images"     # Folder where uploaded media will be stored
public_folder: "/blogposts/images"    # Public URL for accessing media files

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/blogposts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publisher", name: "publisher", widget: "string", required: true }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ" }
      - { label: "Cover Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "faq"  # New FAQ collection
    label: "FAQ"
    folder: "content/faq"  # Folder where FAQ markdown files will be stored
    create: true  # Allows creating new FAQ items
    slug: "{{slug}}"  # Generate slugs for files
    fields:
      - { label: "Question", name: "question", widget: "string", required: true }
      - { label: "Answer", name: "answer", widget: "markdown", required: true }
      - { label: "Category", name: "category", widget: "string", required: false }  # Optional category field
      - { label: "Order", name: "order", widget: "number", required: false }  # Optional order field for sorting
