name: Deploy and Upload to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies and build (if needed)
      - name: Install and build
        run: |
          sudo apt-get install hugo -y
          hugo

      # Step 3: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      # Step 4: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # Step 5: Upload index.html and sync images folder to S3
      - name: Upload index.html and sync images folder to S3
        run: |
          aws s3 cp ./public/blogposts/index.html s3://user-landing-test/news.html --region us-east-2

          aws s3 sync ./public/blogposts/ s3://user-landing-test/blogposts/ --region us-east-2 --exact-timestamps --delete

          aws s3 sync ./public/images/ s3://user-landing-test/blogposts/images/ --region us-east-2 --exact-timestamps --delete

      # Step 6: Invalidate CloudFront Cache
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id E2HJB44CNY8K41 --paths "/*"
